#########################
#####   LumberJack  #####
#########################

#
# LumberJack provides the /lumberjack command, that toggles
# tree gravity per player. Players need the lumberjack.use permission.
# When a player has the lumberjack.force permission, they cannot
# disable tree gravity.
#
# Aliases for /lumberjack:
# - /treegravity
# - /gravity
# - /tg
#

# Whether gravity is enabled by default for new players
# Hint: To force players using gravity, give them
# the lumberjack.force permission
gravity-enabled-by-default: false

# When enabled, tree gravity will only apply when the
# player used an axe to break the log.
must-use-axe: true

# Whether logs attached at the side or diagonally of the tree trunk
# should also fall down
attached-logs-fall-down: true

# Prevents the placement of torches or other non-solid
# blocks inside or under falling logs.
# Also prevents the logs from starting to fall down
# when the first block below the log (except air)
# is not solid.
prevent-torch-exploit: true

# when set to true, players with gravity DISABLED will be
# shown a message on how to enable tree gravity
# when they break a log for the first time.
# consider setting this to true when you disable gravity by default.
# see also -> message-when-breaking-log
show-message-when-breaking-log: true

# when set to true, players with gravity ENABLED will be
# shown a message on how to disable tree gravity
# when they break a log for the first time.
# consider setting this to true when you enable gravity by default.
# see also -> message-when-breaking-log2
show-message-when-breaking-log-and-gravity-is-enabled: false

# when set to true, the messages are shown again when a player
# logs out and back in and then breaks a log again.
show-message-again-after-logout: true

# should we check for updates?
# when enabled, a message is printed in the console if a new
# version has been found, and OPs will be notified when they
# join the server
# When set to true, we will check for updates on startup and every 24 hours
# When set to on-startup, we will only check on startup
# When set to false, don't check for updates
check-for-updates: true

#########################
##### tree blocks  ######
#########################

# You can set the blocks that will be counted as tree part
# Trees will only be counted as trees if all the blocks have
# the same type of wood, e.g. a mixture of acacia and oak
# will not be counted as a whole tree
# Default is all types of logs, wood, stripped log and stripped wood
tree-blocks:
- ACACIA_LOG
- ACACIA_WOOD
- BIRCH_LOG
- BIRCH_WOOD
- DARK_OAK_LOG
- DARK_OAK_WOOD
- JUNGLE_LOG
- JUNGLE_WOOD
- OAK_LOG
- OAK_WOOD
- SPRUCE_LOG
- SPRUCE_WOOD
- STRIPPED_ACACIA_LOG
- STRIPPED_ACACIA_WOOD
- STRIPPED_BIRCH_LOG
- STRIPPED_BIRCH_WOOD
- STRIPPED_DARK_OAK_LOG
- STRIPPED_DARK_OAK_WOOD
- STRIPPED_JUNGLE_LOG
- STRIPPED_JUNGLE_WOOD
- STRIPPED_OAK_LOG
- STRIPPED_OAK_WOOD
- STRIPPED_SPRUCE_LOG
- STRIPPED_SPRUCE_WOOD

# If the tree does not stand on one of the following blocks,
# it will not be counted as a tree.
tree-ground-blocks:
- GRASS_BLOCK
- DIRT
- COARSE_DIRT
- MYCELIUM

#### THIS WILL BE IMPLEMENTED LATER ####
# Parts of the tree that will be counted as leaves
#### THIS WILL BE IMPLEMENTED LATER ####
tree-leaves-blocks:
- ACACIA_LEAVES
- BIRCH_LEAVES
- DARK_OAK_LEAVES
- JUNGLE_LEAVES
- OAK_LEAVES
- SPRUCE_LEAVES

#### THIS WILL BE IMPLEMENTED LATER ####
# Minimum number of leaves that have to be present per log.
# E.g. 0.1 means there has to be at least one block of leaves for every ten logs
#### THIS WILL BE IMPLEMENTED LATER ####
min-leaves-per-log-ratio: 0.1

# Maximum number of air blocks that can be inside the tree trunk
# If more than the specificied number of air blocks are present inside the trunk,
# it will not be counted as a tree
max-air-in-trunk: 1

#########################
#### disabled worlds ####
#########################

# You can disable LumberJack for certain worlds. Each world's name has to
# be on a separate line, starting with a hyphen and followed by a space

# Example:
#
# disabled-worlds:
# - world_nether
# - world_the_end

disabled-worlds:

#########################
##### localization ######
#########################

# Available color codes:
# &0 Black        &6 Gold       &c Red
# &1 Dark Blue    &7 Gray       &d Light Purple
# &2 Dark Green   &8 Dark Gray  &e Yellow
# &3 Dark Aqua    &9 Blue       &f White
# &4 Dark Red     &a Green
# &5 Dark Purple  &b Aqua

# Available formatting codes:
# &k Obfuscated   &m Strikethrough
# &l Bold         &o Italic
# &n Underline    &r Reset

##### English
message-gravity-enabled: "&7Tree gravity has been &aenabled&7."
message-gravity-disabled: "&7Tree gravity has been &cdisabled&7."
message-when-breaking-log: "&7Hint: Type &6/lumberjack&7 to enable tree gravity."
message-when-breaking-log2: "&7Hint: Type &6/lumberjack&7 to disable tree gravity."
message-can-not-disable: "&cYou are not allowed to disable tree gravity."

##### French
#message-gravity-enabled: "&7La gravité d'arbre a été &aactivée&7."
#message-gravity-disabled: "&7La gravité d'arbre a été &cdésactivée&7."
#message-when-breaking-log: "&7Astuce: écris &6/lumberjack&7 pour activer la gravité d'arbre."
#message-when-breaking-log2: "&7Astuce: écris &6/lumberjack&7 pour désactiver la gravité d'arbre."
#message-can-not-disable: "&cVous n'avez pas la permission de désactiver la gravité d'arbre."

##### Dutch - Thanks to Xeyame for translating -> https://github.com/Xeyame
#message-gravity-enabled: "&7Boom-zwaartekracht is &aaan&7 gezet."
#message-gravity-disabled: "&7Boom-zwaartekracht is &cuit&7 gezet."
#message-when-breaking-log: "&7Hint: Tik &6/lumberjack&7 om Boom-zwaartekracht aan te zetten."
#message-when-breaking-log2: "&7Hint: Tik &6/lumberjack&7 om Boom-zwaartekracht uit te zetten."
#message-can-not-disable: "&cHet is niet toegestaan voor je om Boom-zwaartekracht aan te zetten."

#########################
#####     Done!     #####
#########################

# please do not change the following line manually!
config-version: 7
